files:
  - source: /TMessagesProj/src/main/res/values/strings_neko.xml
    translation: /TMessagesProj/src/main/res/values-%android_code%/strings_neko.xml
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in
  - source: /TMessagesProj/src/main/res/values/strings_na.xml
    translation: /TMessagesProj/src/main/res/values-%android_code%/strings_na.xml
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in
  - source: /TMessagesProj/src/main/res/values/strings_nax.xml
    translation: /TMessagesProj/src/main/res/values-%android_code%/strings_nax.xml
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in